### ISSUE TITLE
Thread termination in line 865 of ESPRESSO_S.pl

### ISSUE THREAD

**Issue by jamesoccean** [Xinglab/espresso#13]
Hello,

I am running into an issue where the thread gets terminated: Thread 1 terminated abnormally: 
`Died at ESPRESSO_S.pl line 865, <IN> line 72` 

Here is the command I used: 
`perl ESPRESSO_S.pl -L trial.tsv -F genome.fasta -A genes.gtf -O dRNA_age_out`

I also checked my sorted BAM file because line 865 of https://github.com/Xinglab/espresso/blob/v1.3.0-beta/src/ESPRESSO_S.pl reads:
`die if !exists $chr_seq_len_ref->{$line[2]};`. There does not seem to be an issue with my BAM file (example of BAM file below) but the first line does differ from the SAM file provided in the example.
`c24482d2-30cd-4e1f-9787-3931c1bb6603    16      chr1    3547555 60      98S12M1D34M1D3M1I40M1D14M3I46M1D9M1I6M1I3M2D37M1023N11M2D7M2I58M4D16M1D17M3I48M1D1M1D4M2D6M3I20M3I67M1I10M1D10M1D4M2I41M2005N17M1D1M3D2M1D23M1D35M2I12M1D35M1I30M3I1M1I13M1D22M1I22M3D1M1D6M1D17M1D29M2I13M *       0       0       GAGGAGTTTTAATGGAATGGATGGATGGAATGAATGTGTAATAATGGAATATGTATAAATGGGAATGAAAAACCCTGAAACAGTGTTGCAGTTTCAGGATTCTGTGTGGAACAGATACTTGAACATACCATAGTATTCTCCTCAAACTTCAGGCTTCGTTTATCACAACAGGACACTGCCAACATAGCATTGTTGACAAAGAAAGAGCATCCCTGTGATGAGGGATGTGGCAATCTTCCAGCTGCATTGTCTTTCAATTTAGATTGCAAAGGGACTACTATTGATACCTTTTTGTTTATCTTCACTGTCCTAAGCCTTGGTGATGTTATAGCTGTTATTTTCCAAGAGCTCTCTTTGTCCGCATCAAATTCTCCTTGATTCAGTGAAGATTTTGTTTGTTTCTTATCGTTACTGGTCCACAGCAGCTATGATCAGACCTCACGTAACAAGATCTTTTACATCAGACTTGGTAAGAAGACTGAAAAGATGCAGAGCTGAACAGCTGTGGTGATCCATCACTTACTGACTGCCGCACATCAGTGTCACCGAGCCCGTTTTCGTCCCAGCACAATGGAAAAAGGGCCAGGTAATGATGATTAAGAAACATCATGCATTAAGATGTTTCACAAACTTGCACAGCACCTCAACATGCTGTTTCCCAAATATTGACGTTCAGGAAGCTGTGTTTAGCTATGCCATCAAGCTATAAGCTACGCAGGCATATGAAATCAGATTTGCTCAATTGCATTGGCTAATCATTACTTTGATGAAATCATCAGGACAACAGCATGCAACATTTTCAAGAAGGATATAAAGGTGGGGCTGGGATCAAGAAAGACTAGAACTGACCCAGTGTCCTTTAGAAGGTCTATAACCTTCAGGTCTCAAGACCACAGTGTTCTAAAATAAGAGGCACATCAGTTCCAGCAGA       &%&'%$%*'%))$$$&)&$&%$%$$'''&($$%*$$$$$,*$**)((*)%'%$#(&&(('&(%&*&%%,&+-#%%%%(',..)&&%&&&$%%%)''%.)/667)&)&(//./+((6::A+.)%<667%&*/031:7*0+((('()(21')),;@EA3.B69787;65*48.;02513.*.7'>77.'&*()'''+.3)((&9(.+(0:4:89542(,---(0)+&1239::7)/5A4&'::4789AC=0:4416696.17+(&&&&%(%'(953:4613::;5?<103<?:655::;&.,-&,7<8<,110/6486E43'&(''''(*233064-.559=<14:.((4;<<:'H=:41*),,.4574988320+00749512.-*-+*533:<@;8?:::<9B98B94418:><D+8:<97*''-974597582.222'+,***)*&)'%-35?;>78./465&-5745**6(')&+7471+')&)28775'))*/686?<14<53-2.,4:9;BB92.*&3<9=:/<4691/)9<>=?77-346,+/.233'',0=:54A==56*5)971/0),&1(+(239:;7+)2-++)**-7871((36<94>5*26431*%%',==<5:459=605<2-6::'(2'+'(78985<9=A77:21*33<0088<;:788<=0775.1/1,7:7>99021+1<?=;3<751>;>7+*96=7,8<78;88+/(.,6743(($%/3227:9>8<=@B@>:7;9+'(-+144B42'+))*(31)(,-+)3.,,068/42012-1.&)*1/-**)+)1-,()32).')%/4<839<7'7)50)'&&')<0/%')52;9::=24)&,59:0,,-%*%.-1/.''5:5H>8974745512%%*13//0)&&()2021<534-0*'-)*)(';93?>583%$*(%     NM:i:86 ms:i:604        AS:i:529        nn:i:0  ts:A:+  tp:A:P  cm:i:103        s1:i:498     s2:i:0   de:f:0.0736     MD:Z:6A1A3^C1G32^G0T42^A29T30^T16G1^TA26G21^AA1A0A62^GAAG16^T65^A1^G0T3^AG65T37^G10^A16C0A2A0G40^T1^ATG2^T23^T39G7^G1A18G45T12^G13G0A8T20^GTA1^G6^G0C16^G42   rl:i:28`

Any help to fix this would be very appreciated!

**Comment by EricKutschera** [comment]
The reason for the error is as you posted: `die if !exists $chr_seq_len_ref->{$line[2]};`

That line is checking the chromosome name from the alignment against the chromosome names from the FASTA file given as -F or --fa. That --fa file might differ from what was used to align the reads. You could try editing that line to `die "did not find: $line[2]" if !exists $chr_seq_len_ref->{$line[2]};` and then rerunning to get a better message

I think `<IN> line 72` means that the error occured on the 72nd line of a bam file. If you could check that line you may see that the chromosome name is different than what's in --fa

**Comment by EricKutschera** [comment]
ESPRESSO v1.3.1 should report a better error in cases like this
