### ISSUE TITLE
Espresso quantification without identification

### ISSUE THREAD

**Issue by zzare-umd** [Xinglab/espresso#18]
Hi, 

I wanted to run the Espresso for just quantification with a given annotation without any identification, but I don't know if this is possible or not. I follow the steps that is expressed in the "Basic Usage" section, but the output contains the novel transcripts from espresso. Is there any way I can run only the quantification mode of the espresso?

**Comment by EricKutschera** [comment]
From the README: https://github.com/Xinglab/espresso/tree/v1.3.1

```
perl ESPRESSO_S.pl --help

[...]

-R, --read_ratio_cutoff
      min perfect read ratio for denovo detected candidate splice junctions:
      Set this as 1 for completely GTF-dependent processing (default: 0)
```


The description says 1 is high enough, but actually the check is `>=` the cutoff so the cutoff has to be more than 1 to make the check always fail. If you add `--read_ratio_cutoff 2` when you run the S step and also add `--read_ratio_cutoff 2` when you run the Q step then ESPRESSO should only consider annotated isoforms
