### ISSUE TITLE
System sort commands run out of memory

### ISSUE THREAD

**Issue by chrisamiller** [Xinglab/espresso#24]
The system out calls to `sort` commands can run out of memory when working with large datasets and cause the whole ESPRESSO_C process to die.  Unix sort contains a built in `-S` option that allows you set the buffer size, and it seems like that it could be set to some reasonable value to help prevent this error.

https://github.com/Xinglab/espresso/blob/091f65dd3291c309a6f8840ed2e51cae1b75cd10/src/ESPRESSO_C.pl#LL160C70-L160C70

**Comment by sagnikbanerjee15** [comment]
Hi @chrisamiller,

I think I have the same problem. The ESPRESSO_C step fails without any error. Did you experience something similar?

Thanks.

**Comment by EricKutschera** [comment]
`--sort_buffer_size` is added in v1.4.0 with 2G default
