### ISSUE TITLE
Reference fasta file

### ISSUE THREAD

**Issue by vetmohit89** [Xinglab/espresso#25]
Dear, 

I tested this tool with test data and it works absolutely fine. But I was not able to find these functions in IGV (2.15.2) File -> Load from File -> {sample_name}.bw for each sample
Right click track.
Select "Autoscale".
Select "Maximum" under "Windowing Function".

Also, I am wondering which reference fasta (transcriptome or genome) I should use if I am just interested to know the differential expression of isomers? Can I use transcriptome reference file for this purpose?

Thank you
Mohit

**Comment by EricKutschera** [comment]
I installed IGV 2.15.2 and was able to make the visualization from the example data. Here are screenshots:
![load_from_file](https://github.com/Xinglab/espresso/assets/3375309/578a0889-0268-4d26-a1e9-69a6bd2396f2)

![autoscale_maximum](https://github.com/Xinglab/espresso/assets/3375309/f7accf3f-08bc-4e31-9b46-0592c312c0b5)

You could also try https://github.com/Xinglab/rMATS-long which can make plots from ESPRESSO output

ESPRESSO requires the genome reference fasta

**Comment by vetmohit89** [comment]
Thank you so much for reply. I am getting below warning message when running espresso_S.pl script:

**samtools: /data/user/home/mbansal/.conda/envs/espresso/bin/../lib/libtinfow.so.6: no version information available (required by samtools)
samtools: /data/user/home/mbansal/.conda/envs/espresso/bin/../lib/libncursesw.so.6: no version information available (required by samtools)
samtools: /data/user/home/mbansal/.conda/envs/espresso/bin/../lib/libncursesw.so.6: no version information available (required by samtools)**

Here was my sbatch file
#!/bin/bash
#SBATCH -J espresso.job
#SBATCH -o espresso_1234%j.out
#SBATCH -e espresso_1234P.%j.err
#SBATCH -p pascalnodes-medium
#SBATCH --time=48:00:00
#SBATCH --mem=202400
#SBATCH --ntasks=10
#SBATCH --mail-type=ALL


module load Anaconda3/2022.05
module load SAMtools/1.12-GCC-10.2.0
conda activate espresso

perl ESPRESSO_S.pl \
-L samples.tsv \
-F GRCh38.p13.genome.fa \
-A /gencode.v43.annotation.gtf \
-O shGFP/

I used conda for intalling this tool and package has samtools. So I should not need to load samtools as module. It was giving error. I added samtools module load command and still getting this message.

Thank you
Mohit

**Comment by EricKutschera** [comment]
Those warnings should be safe to ignore. I think it means that samtools didn't find the exact version of those libraries that it was expecting, but it was still able to use those libraries

I was able to install ESPRESSO to a conda environment today and use the samtools installed to that environment without seeing the warnings. You could try installing to a new conda environment to see if the warnings go away

**Comment by vetmohit89** [comment]
Thank you so much Eric. I have only two replicates for each sample. I am wondering if I can still use rmats detect_differential_isoforms.py. Will it work with two samples per group?

Thank you
Mohit

**Comment by EricKutschera** [comment]
I think you should be able to run https://github.com/Xinglab/rMATS-long/blob/main/scripts/detect_differential_isoforms.py if you have two sample groups each with 2 replicates. If you only have 1 replicate in each sample group then you may need to use the latest commit of rMATS-long instead of the v1.0.0 release

**Comment by vetmohit89** [comment]
Dear Eric,

I downloaded rmats this week with conda command and I used https://github.com/Xinglab/rMATS-long/blob/main/scripts/detect_differential_isoforms.py script with one sample per group. But it is giving following error:                    
 
"Error in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  : 
  invalid 'x'
Calls: main ... dmDS_estimateTagwisePrecision -> dm_profileLikModeration -> loess -> simpleLoess
In addition: Warning messages:
1: In base::readLines(connection) :
  incomplete final line found on 'Group_2.txt'
2: In base::readLines(connection) :
  incomplete final line found on 'Group_1.txt'
3: In max(which(not_boundry)) :
  no non-missing arguments to max; returning -Inf
4: In dm_movingAverageByCol(loglik = loglik, mean_expression = mean_expression,  :
  NAs introduced by coercion to integer range
Execution halted
Traceback (most recent call last):
  File "/data/user/home/mbansal/.conda/envs/rmats/rMATS-long/detect_differential_isoforms.py", line 142, in <module>
    main()
  File "/data/user/home/mbansal/.conda/envs/rmats/rMATS-long/detect_differential_isoforms.py", line 138, in main
    detect_differential_isoforms(args)
  File "/data/user/home/mbansal/.conda/envs/rmats/rMATS-long/detect_differential_isoforms.py", line 127, in detect_differential_isoforms
    detect_isoforms(script_dir, args.abundance, args.out_dir, args.num_threads,
  File "/data/user/home/mbansal/.conda/envs/rmats/rMATS-long/detect_differential_isoforms.py", line 82, in detect_isoforms
    rmats_long_utils.run_command(command)
  File "/data/user/home/mbansal/.conda/envs/rmats/rMATS-long/rmats_long_utils.py", line 278, in run_command
    subprocess.run(command, check=True)
  File "/home/mbansal/.conda/envs/rmats/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['Rscript', '/data/user/home/mbansal/.conda/envs/rmats/rMATS-long/detect_differential_isoforms.R', '/data/user/home/mbansal/local/espresso/espre
sso/src/shGFP_33_results/samples_N2_R0_abundance.esp', '/data/user/home/mbansal/local/espresso/espresso/src/shGFP_33_results/', '1', 'Group_2.txt', 'Group_1.txt']' returned non-zero ex
it status 1."
Am I missing anything?
