### ISSUE TITLE
Subprocess.CalledProcessError: Command "bedGraphToBigWig"

### ISSUE THREAD

**Issue by YANG-Jiwei** [Xinglab/espresso#26]
Hi, thank your espresso for a very friendly experience for the beginner like me. But I encountered an error when running the final Visualization. 

The error section showed in two places: 
`subprocess.CalledProcessError:`** Command '['bedGraphToBigWig', 'ITOYO_1_dRNA_Output/visualization/ITOYO_1_dRNA.bed', 'ITOYO_1_dRNA_Output/visualization/Gasterosteus_aculeatus.BROADS1.dna_rm.toplevel.chrom.sizes', 'ITOYO_1_dRNA_Output/visualization/ITOYO_1_dRNA.bw']' returned non-zero exit status 255.`
 and 
`subprocess.CalledProcessError: Command '['/home/yangjiwei/miniconda3/envs/mamba/envs/espresso/bin/python3', '/home/yangjiwei/ITOYO_directRNA/ITOYO_dRNA_Espresso/espresso_v_1_3_2/visualization/make_sample_bigwigs.py', '--abundance-esp', '/home/yangjiwei/ITOYO_directRNA/ITOYO_dRNA_Espresso/Nanoseq_ITOYO_BROAD_bamfile/ITOYO_1_dRNA_Output/ITOYO_dRNA_N2_R0_abundance.esp', '--chrom-sizes', 'ITOYO_1_dRNA_Output/visualization/Gasterosteus_aculeatus.BROADS1.dna_rm.toplevel.chrom.sizes', '--annotation-bed', 'ITOYO_1_dRNA_Output/visualization/ITOYO_dRNA_N2_R0_updated.bed', '--output-dir', 'ITOYO_1_dRNA_Output/visualization']' returned non-zero exit status 1.`

I successfully ran your test data but failed in my data. I just found four number of novel isoforms from a gene according to espresso's output. Is it because too few reads were found that caused the error?

**Comment by EricKutschera** [comment]
The error message shows that there was an issue when running `bedGraphToBigWig` from `make_sample_bigwigs.py`. It doesn't show what the error was. Was there any other error output?

I've seen an error from `bedGraphToBigWig` before related to the input not being sorted. You could try making the change from this branch to see if it resolves the error: https://github.com/Xinglab/espresso/pull/27/files

**Comment by YANG-Jiwei** [comment]
[230718_Yang_Error  information in visualization.txt](https://github.com/Xinglab/espresso/files/12074867/230718_Yang_Error.information.in.visualization.txt)
Thanks for your suggestions. There is still error even though I have tried the revision of make_sample_bigwigs.py. But error information is different this time. It Would be helpful if you can check the whole error information form the attachment. Thank you!

**Comment by EricKutschera** [comment]
This is the new error:
```
  File "/home/yangjiwei/ITOYO_directRNA/ITOYO_dRNA_Espresso/espresso_v_1_3_2/visualization/make_sample_bigwigs.py", line 141
    sort_env = {'LC_COLLATE': 'C'}
IndentationError: unexpected indent
```

That would happen if the number of leading spaces on that line is not as expected. If you manually made the edits from the previous link you can try double checking that the text exactly matches. Or instead of editing the file you can download the version that has the edits: https://github.com/Xinglab/espresso/blob/ac80c229abcc634dcc0865786db63aa59445bf33/visualization/make_sample_bigwigs.py

There is a button on that page to download the raw file

**Comment by YANG-Jiwei** [comment]
Thanks for your timely reply! I copied your new code and now the problem is solved!
