### ISSUE TITLE
ESPRESSO_S out of memory！

### ISSUE THREAD

**Issue by kir1to455** [Xinglab/espresso#30]
Hi,
Thank you for developing ESPRESSO!
I encountered the following issues while running ESPRESSO_S.pl.
My ESPRESSO version is 1.3.2.
Here is my code.
`perl ${ESPRESSO_Dir}/ESPRESSO_S.pl -A ${IndexDir}/gencode.vM33.basic.annotation.gtf -L ${HomeDir}/samples.tsv -F ${IndexDir}/GRCm39.genome.fa -O ${Output_Dir} -T 10`
![image](https://github.com/Xinglab/espresso/assets/87375686/e8d00d7b-63f6-4bbe-9cc8-16305b7f8fc4)
I am sure it is not caused by memory, as my machine has 256GB of memory and it automatically terminates when it occupies 2.2GB of memory.

Could you give me some advice?
Best wishes,
Kirito

**Comment by kir1to455** [comment]
I successfully ran ESPRESSO_S.pl in ESPRESSO1.3.0 version.

**Comment by bingqiWu** [comment]
I met the same problem, too. still not figure out how to solve it.

**Comment by EricKutschera** [comment]
I think the `Out of memory!` message comes from the `Storable` package. ESPRESSO needs Storable version >= 3: https://github.com/Xinglab/espresso/tree/v1.4.0#dependencies
https://perldoc.perl.org/Storable#huge-objects

You can check the version with: `perl -e 'use Storable; print("$Storable::VERSION\n")'`
