### ISSUE TITLE
Thread terminated abnormally

### ISSUE THREAD

**Issue by MSQ-123** [Xinglab/espresso#33]
@EricKutschera , I encountered this problem:

Thread 1 terminated abnormally: chr name (chr1) not recognized for 90:893|0941b403-3d63-43f6-9eb8-edde0ed6224c in IAA.bam at ./espresso_v_1_3_2/src/ESPRESSO_S.pl line 853, <IN> line 69.
Thread 2 terminated abnormally: chr name (chr1) not recognized for 101:356|8a77dbf6-f419-4a66-9cc7-85837fc84655 in PlaB.bam at ./espresso_v_1_3_2/src/ESPRESSO_S.pl line 853, <IN> line 69.

perl ./espresso_v_1_3_2/src/ESPRESSO_S.pl -L samples.tsv -F mm10.fa.gz -A gencode.vM22.annotation.gtf -O test_ChAR/

How could I solve this? I want to avoid this abnormal termination (I got stuck here......, there are limited tools available for alternative splicing analysis for long read data)

**Comment by EricKutschera** [comment]
I think that's happening because mm10.fa.gz is gzipped. ESPRESSO expects an unzipped file for -F

That error can also happen if the chromosome names are different in the input alignment, reference sequence, or annotation

**Comment by MSQ-123** [comment]
I solved this, thank you a lot!
