### ISSUE TITLE
The threads issue for ESPRESSO_Q

### ISSUE THREAD

**Issue by bingqiWu** [Xinglab/espresso#39]
When I runned the command 
`perl ESPRESSO_Q.pl -A hg38.gtf -L samples.tsv.updated -V samples_compatible_isoform.tsv -T 10'
it reported an error
`can't use an undefined value as an ARRAY reference at /soft/espresso_v_1_3_2/src/ESPRESSO_Q_Thread.pm line 1256.'
and generated lots of temporary file, like"thread_chr17_KI270861vl_alt_arguments.tmp"

However, the older release of ESPRESSO is feasible, i.e., espresso-master, which only have single thread.

**Comment by EricKutschera** [comment]
This is the line for that error message: https://github.com/Xinglab/espresso/blob/v1.3.2/src/ESPRESSO_Q_Thread.pm#L1256

The line is trying to sort an array of values that may not exist. I'll work on updating the code to check if there are any values before trying to sort them

However, for newer versions of perl it seems like the behavior ends up being correct in that the code treats it the same as having an empty array. I tried a few perl versions and it seems like v5.20.3 and later work with the current code. You could try using a newer version of perl to get around the error for now

**Comment by EricKutschera** [comment]
This is fixed in v1.5.0
