### ISSUE TITLE
Headers for `sj_list` `chr*_SJ_simplified.list`

### ISSUE THREAD

**Issue by sridhar0605** [Xinglab/espresso#41]
Hi, 

Could you please comment on the col header for those two files? either in the readme or in this thread...

I am trying to replicate the text from espresso paper.
```we used ESPRESSO results generated on long-read data of the same sample to count the number of long reads carrying the inclusion junction (inclusion reads, I) and the number of long reads carrying the skipping junction (skipping reads, S). Similarly, for each exon skipping event detected by rMATS from short-read data of a given cell line replicate, we used ESPRESSO results for long-read data of the same sample to count the number of long reads harboring the cassette exon (inclusion reads, I) and the number of long reads in which the cassette exon is skipped (skipping reads, S). ```

Wondering if `sj.list` is the right file to get junctions counts?!

Thank you
-S

**Comment by EricKutschera** [comment]
This post describes those files https://github.com/Xinglab/espresso/issues/37

The SJ_simplified_list files include the number of reads for each splice junction. The sj.list files have all the read IDs for each splice junction

**Comment by sridhar0605** [comment]
Thanks @EricKutschera ! Closing this for now.
