### ISSUE TITLE
The use of espresso

### ISSUE THREAD

**Issue by junjiemama** [Xinglab/espresso#43]
Hello, can I use espresso to analyze Pacbio seq data? After reading the paper, I got an impression that the pipeline is designed for the Nanopore seq. I really enjoyed using this pipeline, but I just want to make sure that I am using it for the correct dataset.
Thank you very much!

**Comment by EricKutschera** [comment]
Yes, you can use ESPRESSO with Pacbio data. ESPRESSO only requires aligned long reads and genome reference files as input. ESPRESSO was developed using Nanopore data, but aligned reads from Pacbio should also work fine

**Comment by junjiemama** [comment]
Thank you for your fast reply! It is good to hear the confirmation.
