### ISSUE TITLE
run test errors

### ISSUE THREAD

**Issue by Jean497** [Xinglab/espresso#44]
$ ./run_tests 
Traceback (most recent call last):
  File "espresso-main/tool/tests/runner.py", line 3, in <module>
    import tests.alignments.test as alignments_test
  File "espresso-main/tool/tests/alignments/test.py", line 5, in <module>
    import tests.base_test
  File "espresso-main/tool/tests/base_test.py", line 14
    DEFAULT_INTRON_LENGTH = (100, 1_000)
                                      ^
SyntaxError: invalid syntax

I like your pipeline, but there is some test errors in your scripts

**Comment by EricKutschera** [comment]
Here's the line for that error: https://github.com/Xinglab/espresso/blob/v1.4.0/tests/base_test.py#L14

It's using `_` to separate the thousands in `1_000`. That feature is added in python3.6: https://peps.python.org/pep-0515/
If you use python version 3.6 or later then that error should go away
