### ISSUE TITLE
Sequence fasta file corresponding to the final output GTF file

### ISSUE THREAD

**Issue by seongwoohan** [Xinglab/espresso#48]
Hi,

I am aware sample_N2_R0_updated.gtf is an updated GTF annotation for detected isoforms, but is there an actual sequence in a fasta file corresponding to that gtf file? Is there a way to get that file as part of the final output?

Thank you!

**Comment by EricKutschera** [comment]
sample_N2_R0_updated.gtf uses coordinates based on the (-F, --fa) FASTA file that was used as input. It looks like `gffread` can extract sequence info using a GTF and FASTA:

```
conda create --prefix ./new_conda_env
conda activate ./new_conda_env
conda install -c bioconda -c conda-forge gffread
gffread -g {/path/to/reference.fasta} -w ./output.fasta -W {/path/to/sample_N2_R0_updated.gtf}
```
