### ISSUE TITLE
Thread terminated abnormally for ESPRESSO_Q

### ISSUE THREAD

**Issue by shiny-prize** [Xinglab/espresso#49]
Hello while running my nanopore data by ESPRESSO_Q, there are some errors.

My command is like below : 
perl /data/Storage_DAS02/home2/shinsy/.conda/pkgs/espresso-1.4.0-hdfd78af_0/bin/ESPRESSO_Q.pl -A ../reference/gencode.v21.annotation.gtf -L cancer_samples.tsv.updated -V cancer_compatible_isoform.tsv

Thread 5 terminated abnormally: call for /data/Storage_DAS02/home2/shinsy/.conda/envs/espresso/bin/perl /data/Storage_DAS02/home2/shinsy/.conda/pkgs/espresso-1.4.0-hdfd78af_0/bin/ESPRESSO_Q_Thread.pm ./thread_shared_arguments.tmp ./thread_chr11_arguments.tmp exited with return_code: 9
Exiting due to error in worker thread
Perl exited with active threads:
        4 running and unjoined
        0 finished and unjoined
        0 running and detached

Thank you for your help.

**Comment by EricKutschera** [comment]
Can you post the full output from the command? The error message is `Thread 5 terminated abnormally`. Usually there is another error message printed out before that one which gives a reason. Another possibility is that the thread ran out of memory. You could try watching the memory usage in `htop` when ESPRESSO is running to see how much memory it's using

**Comment by shiny-prize** [comment]
Thank you for your attention. Actually, I just solved the problem by using just only one thread. Maybe it could be a problem for our computer sever or etc.
