### ISSUE TITLE
speed up ESPRESSO_C

### ISSUE THREAD

**Issue by chilampoon** [Xinglab/espresso#5]
Hi there, I am running espresso and `ESPRESSO_C` takes a very long time which basically building a lot of blast db. I wonder if you could speed up this step..? thanks!

**Comment by EricKutschera** [comment]
Individual `ESPRESSO_C` jobs can take several days depending on the dataset. As you mentioned, a lot of the time is spent running blast

The main solution to address this in the current implementation (v1.3.0) is to split the work of the `ESPRESSO_C` step over multiple jobs and multiple threads within each job. The main README describes running the individual commands: https://github.com/Xinglab/espresso/tree/v1.3.0-beta#basic-usage

Those instructions will use the default 5 threads for each `ESPRESSO_C` job and will run a separate job for each input .sam file. The snakemake includes an additional step to split the reads among `ESPRESSO_C` jobs according to a config value `target_reads_per_espresso_c_job`: https://github.com/Xinglab/espresso/blob/v1.3.0-beta/snakemake/snakemake_config.yaml#L28

If you have access to a compute cluster then using the snakemake and setting that config value can reduce the time for your ESPRESSO jobs to finish

**Comment by chilampoon** [comment]
@EricKutschera thanks for pointing me to snakemake, i am running on a cluster and it uses LSF that uses bsub commands sort of things. I am new to LSF and I am still exploring how to set those bsub parameters...
It seems to me that it's easier to directly run your split py script then submit jobs because I am not so familiar with snakemake as well... but I may play with snakemake at some point

**Comment by EricKutschera** [comment]
v1.5.0 improves the speed of the C step
