### ISSUE TITLE
Detecting isoforms with unannotated exon

### ISSUE THREAD

**Issue by yichao-cai** [Xinglab/espresso#50]
Thanks @EricKutschera a lot for the excellent tools. (Have been a huge fan of your rMATS work)

May I know whether ESPRESSO is capable of detecting novel isoforms with novel exon that are not annotated in gencode GTF? 

I saw in the README page, ESPRESSO can output:
> `sample_N2_R0_updated.gtf` is an updated GTF annotation for detected isoforms.
> * Each detected isoform is reported as a transcript.
> * The source column indicates for each isoform whether it is a "novel_isoform" or an "annotated_isoform".

For the novel isoform here, is it just the isoform of new arrangement of annotated exons found in the supplied gencode GTF? Or it can also output isoform with unannotated exons

**Comment by EricKutschera** [comment]
Yes, ESPRESSO can detect novel isoforms with exons that are not annotated in the GTF. The GTF argument to ESPRESSO is actually optional. ESPRESSO determines a set of high confidence splice junctions that are either from the GTF or from input alignments where there are no mismatches in the alignment around the splice junction. Then ESPRESSO can report a novel isoform as long as all of the splice junctions in that isoform are high confidence and there are supporting reads for that novel isoform
