### ISSUE TITLE
the number of genes decreased

### ISSUE THREAD

**Issue by Yumy526** [Xinglab/espresso#54]
When I use rmatslong visualized the results, I found that the number of genes was only 200+, which was very strange
I'm not quite sure why this problem happened, I kindly ask for your help.

**Comment by Yumy526** [comment]
I realized the problem, thank you very much

**Comment by Yumy526** [comment]
After my repeated attempts, I found the problem as follows

my samples.tsv.updated is ：
/public/home/ymwang/PacBio/6_bambu/bam/twocellsingle/diymatrix/sam/2cell_13B.sam	2cell_13
	5
/public/home/ymwang/PacBio/6_bambu/bam/twocellsingle/diymatrix/sam/2cell_11A.sam	2cell_11
	2
/public/home/ymwang/PacBio/6_bambu/bam/twocellsingle/diymatrix/sam/2cell_13A.sam	2cell_13
	4
/public/home/ymwang/PacBio/6_bambu/bam/twocellsingle/diymatrix/sam/2cell_10A.sam	2cell_10
	0
/public/home/ymwang/PacBio/6_bambu/bam/twocellsingle/diymatrix/sam/2cell_10B.sam	2cell_10
	1
/public/home/ymwang/PacBio/6_bambu/bam/twocellsingle/diymatrix/sam/2cell_11B.sam	2cell_11
	3

When I changed the file to：
/public/home/ymwang/PacBio/6_bambu/bam/twocellsingle/diymatrix/sam/2cell_13B.sam	2cell
	5
/public/home/ymwang/PacBio/6_bambu/bam/twocellsingle/diymatrix/sam/2cell_11A.sam	2cell
	2
/public/home/ymwang/PacBio/6_bambu/bam/twocellsingle/diymatrix/sam/2cell_13A.sam	2cell
	4
/public/home/ymwang/PacBio/6_bambu/bam/twocellsingle/diymatrix/sam/2cell_10A.sam	2cell
	0
/public/home/ymwang/PacBio/6_bambu/bam/twocellsingle/diymatrix/sam/2cell_10B.sam	2cell
	1
/public/home/ymwang/PacBio/6_bambu/bam/twocellsingle/diymatrix/sam/2cell_11B.sam	2cell
	3

The visualization can go smoothly and gets the right output file.I'm curious about why this is, and I hope to get your answer.What can I do to make it work smoothly according to the division into three groups of 2 different samples each

**Comment by EricKutschera** [comment]
https://github.com/Xinglab/rMATS-long only plots results for transcripts that meet the significance thresholds. Having only 200 significant genes is not necessarily a problem
