### ISSUE TITLE
error with run test

### ISSUE THREAD

**Issue by Xing-2024** [Xinglab/espresso#57]
Hi,
It seems I met a error using the following command:
Command: ./run_tests
Comes out with two errors:

ERROR: test (tests.cd44_example.test.Cd44ExampleTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/test/test_data_espresso_sirv/espresso/tests/cd44_example/test.py", line 53, in test
    self._create_bed_from_gtf()
  File "/data/test/test_data_espresso_sirv/espresso/tests/cd44_example/test.py", line 98, in _create_bed_from_gtf
    tests.base_test.run_command_with_output_and_log(
  File "/data/test/test_data_espresso_sirv/espresso/tests/base_test.py", line 31, in run_command_with_output_and_log
    process = subprocess.run(command,
  File "/usr/local/Anaconda/envs/py3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['paftools.js', 'gff2bed', '/data/test/test_data_espresso_sirv/espresso/tests/cd44_example/data/test_data_espresso_cd44/cd44.gtf']' returned non-zero exit status 126.

======================================================================
ERROR: test (tests.sirv_example.test.SirvExampleTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/test/test_data_espresso_sirv/espresso/tests/sirv_example/test.py", line 38, in test
    self._run_visualization()
  File "/data/test/test_data_espresso_sirv/espresso/tests/sirv_example/test.py", line 178, in _run_visualization
    tests.base_test.run_command_with_log(command, vis_log)
  File "/data/test/test_data_espresso_sirv/espresso/tests/base_test.py", line 20, in run_command_with_log
    process = subprocess.run(command,
  File "/usr/local/Anaconda/envs/py3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/local/bin/python', '/data/test/test_data_espresso_sirv/espresso/visualization/visualize.py', '--genome-fasta', '/data/test/test_data_espresso_sirv/espresso/tests/sirv_example/data/test_data_espresso_sirv/SIRV2.fasta', '--updated-gtf', '/data/test/test_data_espresso_sirv/espresso/tests/sirv_example/out/samples_N2_R0_updated.gtf', '--abundance-esp', '/data/test/test_data_espresso_sirv/espresso/tests/sirv_example/out/samples_N2_R0_abundance.esp', '--target-gene', 'SIRV2', '--minimum-count', '1', '--descriptive-name', 'SIRV', '--output-dir', '/data/test/test_data_espresso_sirv/espresso/tests/sirv_example/out/visualization']' returned non-zero exit status 1.

Anyone has any suggestions?

Thank you.

**Comment by EricKutschera** [comment]
Is there anything written to these files:
`tests/cd44_example/logs/create_bed_from_gtf.log`
`tests/cd44_example/data/test_data_espresso_cd44/cd44.gtf.bed`
`tests/sirv_example/logs/visualization.log`

For the cd44 test maybe `paftools.js` wasn't found on your `$PATH`. Similarly for the sirv test maybe one of the programs needed for the visualization (like `bedGraphToBigWig`) wasn't found

**Comment by Xing-2024** [comment]
Hi, here is the writtings :

> Is there anything written to these files: `tests/cd44_example/logs/create_bed_from_gtf.log` 

#### log: /usr/bin/env: ‘k8’: Permission denied

`tests/cd44_example/data/test_data_espresso_cd44/cd44.gtf.bed` 

####  Nothing here

`tests/sirv_example/logs/visualization.log`
> 
![image](https://github.com/Xinglab/espresso/assets/52621118/85ae6878-33f4-4109-a396-e2848a4e639b)

> For the cd44 test maybe `paftools.js` wasn't found on your `$PATH`. Similarly for the sirv test maybe one of the programs needed for the visualization (like `bedGraphToBigWig`) wasn't found

thank you.

**Comment by EricKutschera** [comment]
`/usr/bin/env: 'k8': Permission denied` is saying that it found `k8` (which is used by `paftools.js`), but the permissions on the file didn't allow you to run it

Similarly `PermissionError: [Errno 13] Permission denied: 'faToTwoBit'` is saying that it found `faToTwoBit` (which is used by the visualization script), but you didn't have sufficient permissions on the file

You could try running `which k8` and `which faToTwoBit` to see the paths to those files. Then when you know the path you can run `ls -l` on those files to see what the permissions are. Maybe those files are owned by another user, or they aren't set as executable

**Comment by kwonej0617** [comment]
Hi @EricKutschera 

I was trying to make a visualization using espresso output using the following code.

```
python3 espresso_code/visualization/visualize.py --genome-fasta reference/hg38.fa --updated-gtf espresso_data/HEK293T-all/HEK293T-all_N2_R0_updated.gtf --abundance-esp espresso_data/HEK293T-all/HEK293T-all_N2_R0_abundance.esp --target-gene ENSG00000146540.15 --minimum-count 1 --descriptive-name ENSG00000146540.15 --output-dir espresso_data/HEK293T-all/
```

However, I got the error message. Could you please explain me what this error is about and how to solve it?
```
Traceback (most recent call last):
  File "espresso_code/visualization/visualize.py", line 186, in <module>
    main()
  File "espresso_code/visualization/visualize.py", line 177, in main
    chrom_sizes = run_fasta_to_chrom_sizes(args.genome_fasta, args.output_dir)
  File "espresso_code/visualization/visualize.py", line 121, in run_fasta_to_chrom_sizes
    subprocess.run(fa_to_two_bit_cmd, check=True)
  File "/usr/lib64/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib64/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'faToTwoBit': 'faToTwoBit'
```

Thank you!

**Comment by EricKutschera** [comment]
The visualization code tries to run this command: https://github.com/Xinglab/espresso/blob/v1.4.0/visualization/visualize.py#L119

The error is saying that it can't find the executable file `faToTwoBit` which is a dependency: https://github.com/Xinglab/espresso/tree/v1.4.0?tab=readme-ov-file#dependencies

You could download it from: http://hgdownload.soe.ucsc.edu/admin/exe/ or it's available from conda: https://github.com/Xinglab/espresso/blob/v1.4.0/snakemake/conda_requirements.txt#L12

If you want to visualize ESPRESSO output you could also try: https://github.com/Xinglab/rMATS-long?tab=readme-ov-file#visualize-isoforms-and-abundance
