### ISSUE TITLE
Error: Don't know what format  is!

### ISSUE THREAD

**Issue by YichaoOU** [Xinglab/espresso#6]
Hello,

Any clue what is wrong? I'm running the test data.

Thanks,
Yichao

```
[yli11@noderome134 test_data]$ perl ../src/ESPRESSO_S.pl -A test_data_espresso_sirv/SIRV_C.gtf -L samples.tsv -F test_data_espresso_sirv/SIRV2.fasta -O test_result
 Work directory test_result does not exist. Make it by myself
 in samples.tsv does not exist or is not readable!
Don't know what format  is!
Perl exited with active threads:
	5 running and unjoined
	0 finished and unjoined
	0 running and detached

```

**Comment by EricKutschera** [comment]
Here is the line for that error message: https://github.com/Xinglab/espresso/blob/v1.3.0-beta/src/ESPRESSO_S.pl#L169

It's expecting samples.tsv to be a tab separated file where the first column in each line is a .sam or .bam file

The error message in your post has an empty space where the file path should be:
```
{file_path} in samples.tsv does not exist or is not readable!
Don't know what format {file_path} is!
```

I was able to reproduce that error message by adding a blank line at the end of my samples.tsv. Does your samples.tsv have a blank line?

**Comment by YichaoOU** [comment]
Yep, thanks!

**Comment by Oliverfeudj** [comment]
Hello @YichaoOU I got a similar error, can you please help me with this? 

`./stress1_of_3weeks.bam sample_name in test.tsv does not exist or is not readable!
Don't know what format ./stress1_of_3weeks.bam sample_name is!
Perl exited with active threads:
        6 running and unjoined
        0 finished and unjoined
        0 running and detached` 

./stress1_of_3weeks.bam is the directory to my bam file and sample_name is its sample name
Thank you
