### ISSUE TITLE
How to find the support reads of novel isoform

### ISSUE THREAD

**Issue by mlpy18** [Xinglab/espresso#63]
In the "samples_N2_R0_abundance.esp" result file, it shows some novel transcript isoform with different expression in each sample, how can we find the support reads for these novel isoform (transcript_ID, such as ESPRESSO:chr8:65795:0)? There are lots of results files after the ESPRESSO analysis was finished, are there any README for these results to help us understand the details?
Thank you very much.

**Comment by EricKutschera** [comment]
The main output files are described here: https://github.com/Xinglab/espresso/tree/v1.4.0?tab=readme-ov-file#output

You can find the reads that were assigned to that novel isoform in sample_N2_R0_compatible_isoform.tsv if you ran the Q step with `-V, --tsv_compt`

**Comment by mlpy18** [comment]
Thank you Eric, we found the reads.
