### ISSUE TITLE
chr name not recognized

### ISSUE THREAD

**Issue by olazaro-ibri** [Xinglab/espresso#65]
Hi there, I've been trying to use espresso to identify novel isoforms for a nanopore dataset I'm working with, I ran through the minimap2 and samtools workflow per the readme (including the sort step), but when I try to run the step with ESPRESSO_S I keep running into the error "Thread 1 terminated abnormally: chr name (NC_000001.11) not recognized for 54a29c81-ce16-4948-ab32-5bb36e907014". I was able to run this step fine with the provided sample data and my reference/annotation files are formatted similarly to the ones provided. Any insight into what might be causing this would be great, thanks!

**Comment by EricKutschera** [comment]
Here's the line for the error: https://github.com/Xinglab/espresso/blob/v1.4.0/src/ESPRESSO_S.pl#L921

It's reading the alignment file, getting the chr name from the 3rd column, and then checking that chr name against what it read from the `-F, --fa` file: https://github.com/Xinglab/espresso/blob/v1.4.0/src/ESPRESSO_S.pl#L242

If you run `grep NC_000001.11 /path/to/file.fasta` do you get any output? You could also try looking for that read ID in your alignment file: `grep 54a29c81-ce16-4948-ab32-5bb36e907014 /path/to/file.sam`. Maybe there is something weird about the formatting for that chr name in one of those files that is causing ESPRESSO to not match things up. Or it could be that the fasta file used with ESPRESSO isn't the same as the file used with minimap2

**Comment by olazaro-ibri** [comment]
Figured it out, fasta with ESPRESSO wasn't the one used with minimap2, that passed. Thanks!
