### ISSUE TITLE
nhmmer has to be 3.3.1?

### ISSUE THREAD

**Issue by YichaoOU** [Xinglab/espresso#7]
Hello,

I got an error in step 2 using the test data. The installation said nhmmer >= 3.3.1, and I have 3.3.2. Is it OK?

```
[yli11@noderome134 test_data]$ perl ../src/ESPRESSO_C.pl -I test_result -F test_data_espresso_sirv/SIRV2.fasta -X 0 -T 5
Please make sure nhmmer 3.3.1 is installed and included in $PATH! at ../src/ESPRESSO_C.pl line 135.

(captureC) [yli11@noderome134 test_data]$ echo $PATH
/hpcf/authorized_apps/rhel7_apps/hmmer/install/3.3.2/bin

(captureC) [yli11@noderome134 test_data]$ which nhmmer
/hpcf/authorized_apps/rhel7_apps/hmmer/install/3.3.2/bin/nhmmer
```

Thanks,
Yichao

**Comment by EricKutschera** [comment]
The code is checking for the version to be exactly 3.3.1: https://github.com/Xinglab/espresso/blob/v1.3.0-beta/src/ESPRESSO_C.pl#L127

That is inconsistent with the README saying hmmer >= 3.3.1

I couldn't find details about what the updates are for 3.3.2 from http://hmmer.org/ but I don't know of any reason 3.3.2 should not work with ESPRESSO. For now you could comment out the line that gives the error or update the version number check in the code. I'll update at least 1 of the README or the version check in the code once I have time to test 3.3.2

**Comment by YichaoOU** [comment]
commented out line 129.

Thanks,
Yichao

**Comment by YichaoOU** [comment]
Cool! I got the example all worked out!

Thanks,
Yichao
