### ISSUE TITLE
361 killed in ESPRESSO_C.pl

### ISSUE THREAD

**Issue by bingqiWu** [Xinglab/espresso#73]
ESPRESSO_C.pl reports the error: 
`361 Killed                 perl ESPRESSO_C.pl -I espresso/temp -F /database/hg38.fa -X 11 -T 20`

the sample has 17 M reads, and applied 170 gb memory with 20 threshold.
Is there not enough memory?

**Comment by EricKutschera** [comment]
I think `Killed` would happen for exceeding memory. Are you using v1.5.0? I would recommend splitting up the C step into smaller jobs either with the snakemake or following: https://github.com/Xinglab/espresso/tree/v1.5.0?tab=readme-ov-file#example-with-split

Also you could use fewer threads. Using 5 threads with `-T 5` should reduce the memory usage

**Comment by bingqiWu** [comment]
> I think `Killed` would happen for exceeding memory. Are you using v1.5.0? I would recommend splitting up the C step into smaller jobs either with the snakemake or following: https://github.com/Xinglab/espresso/tree/v1.5.0?tab=readme-ov-file#example-with-split
> 
> Also you could use fewer threads. Using 5 threads with `-T 5` should reduce the memory usage

Thanks for your reply!

Yes, I did use v1.5.0.
I tried to use `split_espresso_s_output_for_c.py` to split the output of espresso_s according to your suggestion.
But how to run the following ESPRESSO.C_pl if there are more than one sample?
Is that so?
```
perl ESPRESSO_C.pl -I test_split_sirv_c/0 -F test_split_sirv_c/fastas/0.fa -X 0 -T 5
perl ESPRESSO_C.pl -I test_split_sirv_c/1 -F test_split_sirv_c/fastas/1.fa -X 0 -T 5
perl ESPRESSO_C.pl -I test_split_sirv_c/2 -F test_split_sirv_c/fastas/2.fa -X 0 -T 5
perl ESPRESSO_C.pl -I test_split_sirv_c/3 -F test_split_sirv_c/fastas/3.fa -X 0 -T 5

perl ESPRESSO_C.pl -I test_split_sirv_c/0 -F test_split_sirv_c/fastas/0.fa -X 1 -T 5
perl ESPRESSO_C.pl -I test_split_sirv_c/1 -F test_split_sirv_c/fastas/1.fa -X 1 -T 5
perl ESPRESSO_C.pl -I test_split_sirv_c/2 -F test_split_sirv_c/fastas/2.fa -X 1 -T 5
perl ESPRESSO_C.pl -I test_split_sirv_c/3 -F test_split_sirv_c/fastas/3.fa -X 1 -T 5

perl ESPRESSO_C.pl -I test_split_sirv_c/0 -F test_split_sirv_c/fastas/0.fa -X 2 -T 5
perl ESPRESSO_C.pl -I test_split_sirv_c/1 -F test_split_sirv_c/fastas/1.fa -X 2 -T 5
perl ESPRESSO_C.pl -I test_split_sirv_c/2 -F test_split_sirv_c/fastas/2.fa -X 2 -T 5
perl ESPRESSO_C.pl -I test_split_sirv_c/3 -F test_split_sirv_c/fastas/3.fa -X 2 -T 5
``

**Comment by EricKutschera** [comment]
From https://github.com/Xinglab/espresso/tree/v1.5.0?tab=readme-ov-file#example-with-split
`-X 0` is always used after `split_espresso_s_output_for_c.py`

After the S step there are directories by sample. The split script creates new files which can have reads from any number of samples, and a single sample can have its reads split over multiple directories. There is a separate directory for each C job and each has a `0/` sub directory which is why `-X 0` is used

**Comment by bingqiWu** [comment]
ok, I get it. Thanks a lot!

by the way, I ran ESPRESSO.C.pl with 17M reads sample, using 5 threads. And monitored the memory usage at the same time. It found out that peak memory used 152G. finally, ESPRESSO.C.pl finished the job without any error.

on the contrary, 
If I limit the memory usage, it would report another error:
```
Thread 3 terminated abnormally: Failed to run sort --buffer-size=2G --numeric-sort --output=temp/0/realign_20396/SJ_group.fa temp/0/realign_20396/SJ_group.fa.tmp. Exit code is 9 at /espresso_v_1_5_0/src/ESPRESSO_C.pl line 2103.
Exiting due to error in worker thread
