### ISSUE TITLE
The ESPRESSO_S.pl output is a bit strange.

### ISSUE THREAD

**Issue by happypiggyzjx** [Xinglab/espresso#75]
Hi Eric，
Me again.Thank you very much for your previous reply!I'm still working on the last question I asked, but I don't think this is the same question as the last one, hence the new issue.

The 11 folders obtained by running ESPRESSO_S.pl are as follows:
/cold_data/zhaojiaxin/ensembl/espresso_out/0,
/cold_data/zhaojiaxin/ensembl/espresso_out/1,
... ..,
/cold_data/zhaojiaxin/ensembl/espresso_out/11
Strangely enough, only the folder . /0 has a lot of output underneath it (some of the output is shown below), containing folders prefixed with realign_, files prefixed with sam.list, and a sj.list file. The rest of the . /1~. /11 folders have only two output files under them: sam.list3 sj.list
![Snipaste_2024-09-11_09-52-30](https://github.com/user-attachments/assets/88eeb53c-7d8a-4412-9b19-ab902de4d6b9)

I ponder the reason, is it that my samples.tsv file is not in the right format?

The documentation states that the input file for espresso is in .sam format, but I found under the -L option description that it is also possible to have a .bam file as input. Now I have 3 pairs of samples (8vs6, 7vs6, 5vs6), of which the two samples (8, 6), 8vs6, have 3 replicates each (8_rep1, 8_rep2, 8_rep3, 6_rep1, 6_rep2, 6_rep3), and for these two samples, after that, I'll be doing analysis of the differential expression (e.g., calculating deltaPSI values etc.).

Now I'm a bit confused about how samples.tsv should be written, please tell me that I should write one samples.tsv per sample pair (below)(tab separated):
/cold_data/wangduo/minimap2/ONT_GRM_R02.sorted.bam	6_rep1
/cold_data/wangduo/minimap2/ONT_GRM_R08.sorted.bam	6_rep2
/cold_data/wangduo/minimap2/ONT_GRM_R14.sorted.bam	6_rep3
/cold_data/wangduo/minimap2/ONT_GRM_R04.sorted.bam	8_rep1
/cold_data/wangduo/minimap2/ONT_GRM_R10.sorted.bam	8_rep2
/cold_data/wangduo/minimap2/ONT_GRM_R16.sorted.bam	8_rep3

Should I write one samples.tsv for each sample pair (as follows), or should I write all the samples for each of the 3 sample pairs in one samples.tsv (as follows)(tab separated):
/cold_data/wangduo/minimap2/ONT_GRM_R01.sorted.bam	5_rep1
/cold_data/wangduo/minimap2/ONT_GRM_R07.sorted.bam	5_rep2
/cold_data/wangduo/minimap2/ONT_GRM_R13.sorted.bam	5_rep3
/cold_data/wangduo/minimap2/ONT_GRM_R02.sorted.bam	6_rep1
/cold_data/wangduo/minimap2/ONT_GRM_R08.sorted.bam	6_rep2
/cold_data/wangduo/minimap2/ONT_GRM_R14.sorted.bam	6_rep3
/cold_data/wangduo/minimap2/ONT_GRM_R03.sorted.bam	7_rep1
/cold_data/wangduo/minimap2/ONT_GRM_R09.sorted.bam	7_rep2
/cold_data/wangduo/minimap2/ONT_GRM_R15.sorted.bam	7_rep3
/cold_data/wangduo/minimap2/ONT_GRM_R04.sorted.bam	8_rep1
/cold_data/wangduo/minimap2/ONT_GRM_R10.sorted.bam	8_rep2
/cold_data/wangduo/minimap2/ONT_GRM_R16.sorted.bam	8_rep3

Your professional response is much needed~

Best,
happypiggy

**Comment by EricKutschera** [comment]
You only need a single samples.tsv file. The first column is the sam or bam path. The second column is the sample name which will be used as a column header in the final output. You can run all your samples together and use the sample name columns to extract the results

The `realign_` folders are created by ESPRESSO_C and are intermediate files that should be removed automatically if ESPRESSO_C finishes. The `-X` argument of the C step tells it which folder to work on: https://github.com/Xinglab/espresso/tree/v1.5.0?tab=readme-ov-file#example
> The -X parameter identifies which input is being processed. In this example there is only a single target ID (0). If there were multiple inputs then ESPRESSO_C would be run separately for each ID in samples.tsv.updated

**Comment by happypiggyzjx** [comment]
I understand, thank you for your reply ~ have a wonderful day!
