### ISSUE TITLE
No valid read_final.txt can be found.

### ISSUE THREAD

**Issue by happypiggyzjx** [Xinglab/espresso#76]
Hi Eric，
When I try to run the ESPRESSO_Q.pl command, I encounter the following error message:
![bug](https://github.com/user-attachments/assets/be3cbd80-e55c-4ba8-ab96-a1c62e3f4bf0)

This is my run command:
perl /home/zhaojiaxin/anaconda3/envs/espresso/bin/ESPRESSO_Q.pl \
-L /cold_data/zhaojiaxin/ensembl/espresso_out/sample.tsv.updated \
-A /hot_warm_data/wangduo/reference/Homo_sapiens.GRCh38.109.gtf \
-O /cold_data/zhaojiaxin/ensembl/espresso_out/output_q \
-T 20 \
-V /cold_data/zhaojiaxin/ensembl/espresso_out/output_q

This is the files and folders under the folder /cold_data/zhaojiaxin/ensembl/espresso_out:
![out](https://github.com/user-attachments/assets/da1b4238-426f-41b1-aaab-c138579b5795)

This is the contents of folders 0-11:
![0](https://github.com/user-attachments/assets/340f774a-becb-45dd-a1fb-2c63772922c8)
Except for folder 0, there are only two files in folders 1-11: sj.list , sam.list3.

Can you please tell me what the problem is?

Best,
happypiggy

**Comment by EricKutschera** [comment]
The error is `No valid read_final.txt can be found in /cold_data/zhaojiaxin/ensembl/espresso_out/4`. The files like `21_read_final.txt` are the end result of running ESPRESSO_C. If you don't have any read final files under `4/` then the C step was not run for that folder, or the C step had an error. Did you run the C step once for each folder using `-X`? Were there any error messages for those runs?

**Comment by happypiggyzjx** [comment]
It's strange that when I write all the samples to the same file and run them together, I get the problem I described above, but when I run them separately this problem doesn't exist, thanks for your reply!
